import { useCallback } from 'react';
import Head from 'next/head';

import FormFilter from '../../components/Form/FormFilter';

import Input from '../../components/Form/Input';
import Layout from '../../components/Layout';
import TableCliente from '../../components/TableCliente';

import styles from './style.module.scss';
import { useState } from 'react';
import { BuscarClientesFiltroResponse } from '../../service/models/cliente/cliente.model';
import { useEffect } from 'react';
// import { buscarClientesPorFiltro } from '../../service/cliente.service';
import Loader from '../../components/Loader';
import moment from 'moment';

const clientes: BuscarClientesFiltroResponse = {
	data: [
		{
			nomeCliente: 'Organização organizada dos organizadores',
			guid: 'ec7dd36a-9581-4ba0-8f8b-b60498de7f0b'
		},
		{
			nomeCliente: 'Organização organizada dos organizadores',
			guid: 'ec7dd36a-9581-4ba0-8f8b-b60498de7f0b'
		},
		{
			nomeCliente: 'Organização organizada dos organizadores',
			guid: 'ec7dd36a-9581-4ba0-8f8b-b60498de7f0b'
		},
		{
			nomeCliente: 'Organização organizada dos organizadores',
			guid: 'ec7dd36a-9581-4ba0-8f8b-b60498de7f0b'
		},
		{
			nomeCliente: 'Organização organizada dos organizadores',
			guid: 'ec7dd36a-9581-4ba0-8f8b-b60498de7f0b'
		},
		{
			nomeCliente: 'Organização organizada dos organizadores',
			guid: 'ec7dd36a-9581-4ba0-8f8b-b60498de7f0b'
		},
	], count: 6,
	page: 1,
	pages: 1,
	totalCount: 6
}

const Cliente = () => {
	const [clienteLista, setClienteLista] =
		useState<BuscarClientesFiltroResponse>();
	const handleSubmit = useCallback((e: any) => {
		e.preventDefault();
		// buscarClientesPorFiltro({
		// 	CountTotal: true,
		// 	Page: 1,
		// 	itemsPerPage: 10,
		// 	nomeCliente: 'ze',
		// }).then((result) => {
		// 	console.log(result);
		// 	setClienteLista(result);
		// });
	}, []);

	useEffect(() => {
		// buscarClientesPorFiltro({
		// 	CountTotal: true,
		// 	Page: 1,
		// 	itemsPerPage: 10,
		// }).then((result) => {
		// 	console.log(result);
		// 	setClienteLista(result);
		// });
	}, []);

	return (
		<>
			<Head>
				<title>Clientes</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout active={'cliente'}>
				{clientes ? (
					<>
						<div className={`mb-4 py-2 ${styles.titulo}`}>
							<h2>Clientes</h2>
						</div>
						<FormFilter onSubmit={handleSubmit} link="cliente/new">
							<div className="row">
								<div className="col-3">
									<Input
										type="text"
										name="nomeCliente"
										label="Nome Cliente"
									/>
								</div>
								<div className="col-3">
									<Input
										type="date"
										name="dataCadastro"
										label="Data de Cadastro"
										value={moment(
											new Date().toISOString()
										).format('yyyy-MM-D')}
									/>
								</div>
							</div>
						</FormFilter>
						<TableCliente data={clientes} />
					</>
				) : (
					<div className={styles.loader}>
						<Loader />
					</div>
				)}
			</Layout>
		</>
	);
};

export default Cliente;
