import type { NextPage } from 'next';
import Head from 'next/head';

import Dashboard from './dashboard';
import styles from '../styles/Home.module.scss';
import LoginWindow from './login';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Gerenciador de Pedidos</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<LoginWindow />
			</main>
		</>
	);
};

export default Home;
